"""initial1

Revision ID: 635d3d67f960
Revises: 9493ce5296d8
Create Date: 2022-06-24 12:18:21.475257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d3d67f960'
down_revision = '9493ce5296d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('in_t', sa.String(length=40), nullable=False))
    op.add_column('user_details', sa.Column('exit_t', sa.String(length=40), nullable=False))
    op.drop_column('user_details', 'exit_time')
    op.drop_column('user_details', 'in_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('in_time', sa.VARCHAR(length=15), nullable=False))
    op.add_column('user_details', sa.Column('exit_time', sa.VARCHAR(length=15), nullable=False))
    op.drop_column('user_details', 'exit_t')
    op.drop_column('user_details', 'in_t')
    # ### end Alembic commands ###
