"""initial

Revision ID: 9493ce5296d8
Revises: 
Create Date: 2022-06-24 11:54:17.128963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9493ce5296d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('user_details', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('user_details', sa.Column('department', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'department')
    op.drop_column('user_details', 'last_name')
    op.drop_column('user_details', 'first_name')
    # ### end Alembic commands ###
